dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://127.0.0.1:8848
#    username: nacos
#    password: nacos
  nacos:
    service:
      version: 1.0.0
